### ISSUE TITLE
All Links Populate as localhost:port

### ISSUE THREAD

**Issue by x86txt** [lllllllillllllillll/DweebUI#14]
Hi, found your project via Reddit, very neat.

One issue is that on the dashboard, all the container links populate as http://localhost:portNumber, for example portainer is http://localhost:8000, tautulli is http://localhost:8181.

**Comment by lllllllillllllillll** [comment]
Hiya,

Right now the "http://localhost:" portion is static, and for the port number I'm just grabbing the containers first exposed port. 
This was kind of a quick and simple way to have the links work with already existing docker containers.

How did you want it changed? 
Server IP instead of localhost, or were you wanting the option to set the link to something else?

_the code can be found in /components/dashCard.js_

**Comment by lllllllillllllillll** [comment]
@JonnySiHI  Fixed in dev branch. To be included in v0.08.

**Comment by lllllllillllllillll** [comment]
Links now use server IP instead of localhost in v0.08.

**Comment by bcurran3** [comment]
> How did you want it changed? Server IP instead of localhost, or were you wanting the option to set the link to something else?

Default to the server IP with edit as an option. That way FQDN's can be plugged in when behind a reverse proxy. Would be super nice if you put checking labels for other info on the roadmap; i.e. traefik.http.routers.dweebui.rule to get dweebui.domain.tld to use for the link when available. You could check for watchtower labels and a slew of other things too - will keep you busy... ha ha. :-)

Project looks BEAUTIFUL. I'll continue to watch and hope to use soon.

**Comment by lllllllillllllillll** [comment]
@bcurran3 

Custom links are an option within the Settings page now (v0.70-dev).
Commit: 926218ee0e06491565b1af7b7b9131f288e9379e
